services:

  mysql:
    image: mysql:8.4
    container_name: task-mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

    volumes:
      - task-db-data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - task-network

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s


  backend:
    build: ./backend
    container_name: task-backend

    ports:
      - "5000:5000"

    env_file:
      - ./backend/.env

    networks:
      - task-network

    restart: unless-stopped

    depends_on:
      mysql:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s


  frontend:
    build: ./frontend
    container_name: task-frontend

    ports:
      - "5173:5173"

    networks:
      - task-network

    restart: unless-stopped

    depends_on:
      backend:
        condition: service_healthy


volumes:
  task-db-data:


networks:
  task-network: